### ISSUE TITLE
New fixes and changes 

### ISSUE THREAD

**Issue by Tarundbz** [heyudude/Brawl-Stars-Club-Tools#2]
Removed leader board and scores tab, removed leader board script as it was meddling with other scripts, Fixed explevel,
removed extra useless headers in members list, fixed filters, suggestion reworked, removed clash royale related things in page.html, changed royaleapi links with brawlstats, changed club score with club trophies some minor changes(forgot)
[Brawl-Stars-Club-Tools.zip](https://github.com/heyudude/Brawl-Stars-Club-Tools/files/5047618/Brawl-Stars-Club-Tools.zip)

**Comment by heyudude** [comment]
Thanks for the improvements. I will have a look at them! 

One tip for the next time: you included the complete files set. Please include only the changed files please.
Then I can figure out the delta more easily when I have the chance to work on it.

**Comment by heyudude** [comment]
Merged pull requests... checking the code now
